name: Release Please
on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please Action
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major}}.${{ steps.release.outputs.minor}}.${{ steps.release.outputs.patch }}

  # release-helm-chart:
  #   name: Release Chart
  #   needs: release-please
  #   if: ${{ needs.release-please.outputs.release_created == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: arn:aws:iam::127745533311:role/github-actions/plaiground-github-oidc # ARN of the oidc role to assume
  #         aws-region: us-east-1 # region where the helm chart is deployed
  #         mask-aws-account-id: "false"

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v2

  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Publish Helm Chart
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         ECR_REPOSITORY: gitops-standard-chart
  #         VERSION: ${{ needs.release-please.outputs.version }}
  #       run: |
  #         helm package .;
  #         helm push $ECR_REPOSITORY-$VERSION.tgz oci://$ECR_REGISTRY/
